org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

org.gradle.tooling.parallel=true

CREDISAFE_API_DEBUG_URL=https://credisafeandroid.onrender.com/v1/
CREDISAFE_API_RELEASE_URL=https://credisafeandroid.onrender.com/v1/

CREDISAFE_VERSION_CODE=26
CREDISAFE_VERSION_NAME=2.7.0-beta.2
